StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{649619C88994FD0F}" {
   Id "SPC_Vehicle_Cougar_4x4"
   Target_en_us "Cougar H MRAP"
   Modified 1687561224
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{649619C88A71B29F}" {
   Id "SPC_Vehicle_Cougar_6x6"
   Target_en_us "Cougar MRAP"
   Modified 1687561230
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{649619CEDA667C08}" {
   Id "SPC_Vehicle_Turret_OGPK"
   Target_en_us "OGPK"
   Modified 1687560812
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{649619CED1A8F8A9}" {
   Id "SPC_Weapon_M2HB"
   Target_en_us "M2HB"
   Modified 1687560821
   Author "mikia"
   LastChanged "mikia"
  }
 }
}